package com.android.rockages.kordx.services.i18n

import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.io.InputStream

class Translation(container: _Container) : _Translation(container) {
 companion object {
 private val json = Json { ignoreUnknownKeys = true }

 /**
 * \u2014 the previous implementation used
 * `json.decodeFromStream<_Container>(input)`, which delegated
 * to the generated `kotlinx.serialization` `@Serializable`
 * `$$serializer` for `_Container` and `_Keys`. The
 * `_Keys.serializer().deserialize` method has 247 fields, and
 * the generated bytecode exceeds the dalvik split-verifier's
 * "argument register" check on API 34, producing
 * `java.lang.VerifyError: Verifier rejected class ..._Keys$$serializer`
 * at app startup (the MainActivity can't be created because
 * the KordX ViewModel can't be instantiated).
 *
 * The fix: deserialize via `JsonObject` and call the
 * `data class` primary constructor via Java reflection
 * (`Class.getDeclaredConstructor(...).newInstance(...)`).
 * The Kotlin reflection path (`KClass.constructors.first()`)
 * would need `kotlin-reflect.jar` on the classpath, which
 * is not bundled; the Java reflection path uses only the
 * Android stdlib.
 *
 * The runtime cost is one reflective call per field; this is
 * acceptable because the loader runs once at app start (the
 * result is cached in [com.android.rockages.kordx.services.i18n.Translator]).
 *
 * the dalvik verifier bug context, the investigation that
 * traced the crash to `_Keys.serializer().deserialize`, and
 * the trade-off (reflection vs. generated bytecode size).
 */
 @OptIn(ExperimentalSerializationApi::class)
 fun fromInputStream(input: InputStream): Translation {
 val root: JsonObject = json.parseToJsonElement(input.readBytes().decodeToString())
 .jsonObject
 val locale = _Locale(
 display = localeString(root, "display"),
 native = localeString(root, "native"),
 code = localeString(root, "code"),
 direction = localeString(root, "direction"),
 )
 val keysObj = root["keys"]?.jsonObject
 ?: error("Translation JSON: missing 'keys' object")
 val keys = buildKeys(keysObj)
 return Translation(_Container(locale, keys))
 }

 private fun localeString(root: JsonObject, field: String): String =
 root["locale"]?.jsonObject?.get(field)?.jsonPrimitive?.content
 ?: error("Translation JSON: missing locale.$field")

 /**
 * Build a `_Keys` instance from a `JsonObject` of all
 * translations via Java reflection. The constructor is
 * cached in a `lazy` block (the loader runs once per locale
 * change, so the cache is hot for subsequent loads). Keys are
 * looked up by name; if a key is missing in the JSON, the
 * empty string is used (the `ignoreUnknownKeys` JSON config
 * tolerates extra keys, but missing keys surface as empty
 * strings \u2014 same behavior as the previous `@Serializable`
 * loader which defaulted to `null`, then `null` was treated
 * as the empty string by the consumer code).
 *
 * See [buildKeys] for the name-source strategy (constructor
 * parameter names via `-java-parameters` as the primary,
 * `getDeclaredFields()` only as an emergency fallback).
 */
 private val keysConstructor: java.lang.reflect.Constructor<*> by lazy {
 _Keys::class.java.declaredConstructors.first { ctor ->
 ctor.parameterCount > 0
 }
 }


 // ROOT CAUSE FIX — `buildKeys` constructs the; generated `_Keys` data class (251 fields) by mapping; each JSON key to a primaryconstructor parameter BY NAME.; The original implementation read the constructor parameter; names via `java.lang.reflect.Parameter.getName()`, which; only returns the real names (e.g. "Songs") when the class; file carries the standard JVM `MethodParameters` attribute.; Kotlin does NOT emit that attribute by default — parameter; names live only inside the `@Metadata` annotation that stock; Java reflection ignores — so every `Parameter.getName()`; returned a synthetic `"p0"`, `"p1"`, …, every `obj[name]`; lookup missed, and every `context.kordx.t.*` translation; resolved to the empty string (the "missing text" bug,; `text=""` for every Compose `Text` sourced from i18n).
 //

 // The build now passes `javaparameters` (see; `app/build.gradle.kts` kotlinOptions) so kotlinc emits; `MethodParameters` and `Parameter.getName()` returns the; real names — in constructor parameter order, which is the; CORRECT order for `newInstance(*args)`. This is the; primary name source.
 //

 // Why NOT use `_Keys::class.java.declaredFields()` order instead; (an earlier draft of this fix did, as a flagindependent; fallback)? Because `getDeclaredFields()` order is NOT; guaranteed to match the primaryconstructor parameter order; — empirically on this generated `_Keys` (251 fields) the; field order differed from the constructor order, which; shuffled every JSON value into the wrong field: the AVD then; rendered nonempty but WRONG labels (the bottom nav showed; "Favorite" / "Add to playlist" / "Hello there!" instead of; "Songs" / "Albums" / …). So fieldnamebyindex is; incorrect; only constructorparameter order (via the now; real `Parameter.getName()`) places values correctly. The; fieldname list is kept only as an emergency fallback for; the unlikely case the build flag is absent AND parameter; names come back synthetic — better nonempty (even if; shuffled) than a fullyblank UI, and the flag is always on; in practice.
 private val keysCtorParamCount: Int by lazy { keysConstructor.parameterCount }

 private val keysCtorParamNames: List<Pair<String, Boolean>> by lazy {
 keysConstructor.parameters.map { it.name to it.isNamePresent }
 }

 private val keysFieldNames: List<String> by lazy {
 _Keys::class.java.declaredFields
 .filter { !java.lang.reflect.Modifier.isStatic(it.modifiers) && !it.isSynthetic }
 .map { it.name }
 }

 private fun buildKeys(obj: JsonObject): _Keys {
 val ctor = keysConstructor
 val paramCount = keysCtorParamCount
 val ctorNames = keysCtorParamNames
 val allCtorNamesPresent = ctorNames.all { it.second }

 // Primary: real constructor parameter names (requires; `javaparameters`, always on per build.gradle.kts).; Correct ORDER by construction (we iterate ctor.parameters).
 val names: List<String?> = when {
 allCtorNamesPresent -> ctorNames.map { it.first }
 keysFieldNames.size == paramCount -> {

 // Emergency fallback only (flag absent): field names; may be in a different order than the constructor,; risking shuffled values. Nonempty is the lesser; evil vs. a fullyblank UI when the flag is off.
 keysFieldNames
 }
 else -> List(paramCount) { null }
 }
 val args = Array<Any?>(paramCount) { idx ->
 val name = names.getOrNull(idx)
 if (name == null) {
 "" // last-resort positional fallback
 } else {
 obj[name]?.jsonPrimitive?.content ?: ""
 }
 }
 @Suppress("UNCHECKED_CAST")
 return ctor.newInstance(*args) as _Keys
 }
 }
}
